In [147]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [148]:
# 读取数据集
data_train = pd.read_csv('../DataSet/titanic/train.csv')
data_test = pd.read_csv('../DataSet/titanic/test.csv')

# 处理数据
data_train = data_train.drop(['PassengerId', 'Name', 'Sex', 'Cabin', 'Embarked', 'Ticket'], axis=1)
data_test = data_test.drop(['PassengerId', 'Name', 'Sex', 'Cabin', 'Embarked', 'Ticket'], axis=1)

# 获取训练集的结果
data_train_result = data_train.loc[:, 'Survived']
data_train = data_train.drop(['Survived'], axis=1)



# 打印数据集的前几行
print(data_train_result.head())
print('------------')
print(data_train.head())
print('------------')
print(data_test.head())

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64
------------
   Pclass   Age  SibSp  Parch     Fare
0       3  22.0      1      0   7.2500
1       1  38.0      1      0  71.2833
2       3  26.0      0      0   7.9250
3       1  35.0      1      0  53.1000
4       3  35.0      0      0   8.0500
------------
   Pclass   Age  SibSp  Parch     Fare
0       3  34.5      0      0   7.8292
1       3  47.0      1      0   7.0000
2       2  62.0      0      0   9.6875
3       3  27.0      0      0   8.6625
4       3  22.0      1      1  12.2875


In [149]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc1 = torch.nn.Linear(5, 4)
        self.fc2 = torch.nn.Linear(4, 1)
        self.sigmoid = torch.nn.Sigmoid()
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.sigmoid(x)
        return x

In [150]:
model = Model()
criterion = torch.nn.BCEWithLogitsLoss(reduction='mean')
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [151]:

for epoch in range(50):
    for i, data in enumerate(data_train.values, 0):
        inputs = data
        print(inputs)

        """ y_pred = model(inputs)
        loss = criterion(y_pred, result)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f"Epoch: {epoch+1}, Batch: {i+1}, Accuracy: {loss.item()}") """


[ 3.   22.    1.    0.    7.25]
[ 1.     38.      1.      0.     71.2833]
[ 3.    26.     0.     0.     7.925]
[ 1.  35.   1.   0.  53.1]
[ 3.   35.    0.    0.    8.05]
[3.        nan 0.     0.     8.4583]
[ 1.     54.      0.      0.     51.8625]
[ 3.     2.     3.     1.    21.075]
[ 3.     27.      0.      2.     11.1333]
[ 2.     14.      1.      0.     30.0708]
[ 3.   4.   1.   1.  16.7]
[ 1.   58.    0.    0.   26.55]
[ 3.   20.    0.    0.    8.05]
[ 3.    39.     1.     5.    31.275]
[ 3.     14.      0.      0.      7.8542]
[ 2. 55.  0.  0. 16.]
[ 3.     2.     4.     1.    29.125]
[ 2. nan  0.  0. 13.]
[ 3. 31.  1.  0. 18.]
[3.      nan 0.    0.    7.225]
[ 2. 35.  0.  0. 26.]
[ 2. 34.  0.  0. 13.]
[ 3.     15.      0.      0.      8.0292]
[ 1.  28.   0.   0.  35.5]
[ 3.     8.     3.     1.    21.075]
[ 3.     38.      1.      5.     31.3875]
[3.      nan 0.    0.    7.225]
[  1.  19.   3.   2. 263.]
[3.        nan 0.     0.     7.8792]
[3.        nan 0.     0.     7.8958]
